### ISSUE TITLE
[BUG] Tab Reload Doesn't Work

### ISSUE THREAD

**Issue by Spontini** [NipoCN/TabModifier#6]
It says "Error occurred while executing command: No value present" everytime i try to use tab reload

**Comment by Shiunin** [comment]
I have this same issue occasionally:

[19:35:55] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=tabmodifier, name=Tab Modifier, version=1.2.0-SNAPSHOT, description=A Simple Tab Manager Plugin
sed on Luckperms, source=./mods/TabModifier-1.3.0-SNAPSHOT.jar}
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_181]
        at xin.omen.tabmodifier.utils.Utilities.updateTargetPlayer(Utilities.java:125) ~[Utilities.class:?]
        at xin.omen.tabmodifier.TabModifier.refresh(TabModifier.java:89) ~[TabModifier.class:?]
        at xin.omen.tabmodifier.TabModifier.onPlayerJoin(TabModifier.java:74) ~[TabModifier.class:?]
        at org.spongepowered.common.event.listener.JoinListener_TabModifier_onPlayerJoin135.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.6-RC3616]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3616]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3616]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3616]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3616]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) [SpongeEventManager.class:1.12.2-2768-7.1.6-RC3616]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:246) [SpongeImpl.class:1.12.2-2768-7.1.6-RC3616]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1681) [pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
